### ISSUE TITLE
Error when running npm start - ValidationError: data should NOT have additional properties

### ISSUE THREAD

**Issue by njmurarka** [ripple/rippled-historical-database#133]
Hello.

So I have almost got the product running.

I tried "node api/server.js" and effectively nothing happened. I checked and I do not think anything is running in the background.

I ran npm start and got the following:

npm start

> rippled-historical-database@2.3.2 start /home/charts/rippled-historical-database
> nodemon api/index.js

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node api/index.js`

/home/charts/rippled-historical-database/node_modules/ripple-lib/dist/npm/common/schema-validator.js:43
    throw new ValidationError(ajv.errorsText());
    ^
ValidationError: data should NOT have additional properties
    at ValidationError.RippleError (/home/charts/rippled-historical-database/node_modules/ripple-lib/dist/npm/common/errors.js:36:13)
    at new ValidationError (/home/charts/rippled-historical-database/node_modules/ripple-lib/dist/npm/common/errors.js:180:115)
    at Object.schemaValidate (/home/charts/rippled-historical-database/node_modules/ripple-lib/dist/npm/common/schema-validator.js:43:11)
    at Object.wrapper [as apiOptions] (/home/charts/rippled-historical-database/node_modules/ripple-lib/node_modules/lodash/index.js:3592:19)
    at new RippleAPI (/home/charts/rippled-historical-database/node_modules/ripple-lib/dist/npm/api.js:95:21)
    at new Server (/home/charts/rippled-historical-database/api/server.js:46:19)
    at Object.<anonymous> (/home/charts/rippled-historical-database/api/index.js:9:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3
[nodemon] app crashed - waiting for file changes before starting...

Help would be appreciated. 

Thank you.

**Comment by njmurarka** [comment]
Any potential help here, please?

**Comment by BeBeMo** [comment]
Hello，njmurarka 
I have the same problem,have you solved it?
Could you give me some suggestions?
