### ISSUE TITLE
TypeError: Cannot read property 'max_sockets' of undefined

### ISSUE THREAD

**Issue by roma4u** [ripple/rippled-historical-database#176]
Guys, after npm instal - I write npm start  and ...

error this.max_sockets = options.max_sockets || 1000
                              ^
TypeError: Can not read property 'max_sockets' of undefined
    at HbaseClient (/home/build/rippled-historical-database/lib/hbase/hbase-thrift/index.js:53:30)
    at new HbaseClient (/home/build/rippled-historical-database/lib/hbase/index.js:7:9)
    at Object.<anonymous> (/home/build/rippled-historical-database/lib/hbase/index.js:21:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/build/rippled-historical-database/api/routes/getLedger.js:6:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

npm -v
5.6.0
node -v
v8.11.4

Can I run the application in a container? Tell me how to do this with the correct ports, so that on request get the response from http://ip/v2/payments

**Comment by shekenahglory** [comment]
You need to copy the example config file, and put it the correct info to point to your hbase cluster
